### ISSUE TITLE
Consider adding JS Unit tests

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#106]
https://github.com/jasmine/jasmine + https://github.com/joescii/sbt-jasmine-plugin (https://github.com/guardian/sbt-jasmine-example)

**Comment by FRosner** [comment]
https://github.com/syntagmatic/underscore.math/blob/master/test.html

**Comment by FRosner** [comment]
I don't know what a good practice would be to integrate jasmine suites into my sbt workflow. In order to test my javascript code, I see two options:
1. I could just access the raw js files in the resource folder.
2. The tests are executed on the served js files after starting the web server.

When DDS is used, the js files being served by an embedded web server. Does that mean that the tests should also use the js files provided by the web server? It might be an advantage to do it like this because then I can test the actual interaction with the DOM of the real page as well.

Whatever option I decide to use, it must integrate into the sbt test phase and trigger the build to fail in case of failing tests.

**Comment by FRosner** [comment]
@Husterknupp any ideas?

**Comment by Husterknupp** [comment]
@FRosner please find some answers in the email I sent you.
