### ISSUE TITLE
Show schema of RDD with show()

### ISSUE THREAD

**Issue by ghost** [FRosner/spawncamping-dds#128]
Integrate schema information into show() output.

**Comment by FRosner** [comment]
@baek86 Easiest way to accomplish this without changing any front-end code would be to add the schema (type and whether it is nullable) to the column name. To avoid blowing up the headers, however, it might make sense to use abbreviations.

What do you think about something like `Age [S*]`, where `*` stands for nullable and `S` for String. We would need to create a mapping between the available types in the meta store and the abbreviations.

**Comment by ghost** [comment]
@FRosner Is there a fixed number of data types or are there possibly unlimited? Does nullable means with missing values? Should we have a separate symbol if there are only missing values?

**Comment by FRosner** [comment]
@baek86 
Please find the number of possible types for Spark 1.2.0 [here](https://github.com/apache/spark/blob/v1.2.0/sql/core/src/main/scala/org/apache/spark/sql/package.scala). There are the basic types for primitives, sequences and structs.

Nullable columns can contain missing values, yes.

Problem with the symbol for columns with only missing values is, that the table only contains a sample of the data. So without any further analysis you can't tell whether the rest of the RDD also has only missing values. I think for now it is fine to show everything that is available in the schema w/o any additional effort.

**Comment by ghost** [comment]
@FRosner 
Thanks for the information. I agree with your suggestion of showing something like `Age [S*]`. We could sit together for the mapping if you want.

**Comment by FRosner** [comment]
@baek86 ok thanks! I will let you know once I pick up this issue and we can discuss the mapping. Another possibility would be that we pair on the whole issue and you fix it :) Just LMK

**Comment by FRosner** [comment]
https://spark.apache.org/docs/1.2.0/sql-programming-guide.html#spark-sql-datatype-reference

**Comment by FRosner** [comment]
Proposed type naming: Take type name (e.g. IntegerType), convert to String and remove trailing "Type" (e.g. Integer).

**Comment by FRosner** [comment]
Nullable columns should have a `*` behind. E.g. `Integer*` if the integer column is nullable.

**Comment by FRosner** [comment]
We should increase the default column width so the column type information also fits.
