### ISSUE TITLE
Tune force layout

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#152]
**Problem**

Currently, I use the D3 force layout with only default parameters and randomly initialized node positions. However, this leads to layouts which are not very readable in most cases. Especially if there are multiple connected components, they are all just placed on top of each other.

**Proposed Solutions**
- http://grokbase.com/t/gg/d3-js/138rrc47cd/initial-positioning-and-isolated-nodes-in-force-direct-graph
- http://www.d3noob.org/2013/03/d3js-force-directed-graph-example-basic.html

**Comment by FRosner** [comment]
I might also want to look at http://stackoverflow.com/questions/17166016/d3-js-controlling-initial-animation-in-force-layout

**Comment by zhdchen** [comment]
@FRosner change is done and checked into github

**Comment by FRosner** [comment]
@zhdchen thanks for the contribution! I merged your branch to master, but I reduced the charge a little bit to save some space.
