### ISSUE TITLE
Add useful titles to dashboard tiles

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#164]
We should make the dashboard more readable by adding titles to the individual tiles.
- Table does not need a title
- Correlation and Mutual Information should have one to understand what the matrix is showing
- Each column statistics should have the name of the column as well

---

Depends on: #148 #160

**Comment by Husterknupp** [comment]
@FRosner this function is gonna be super helpful!

**Comment by FRosner** [comment]
@Husterknupp I hope so! :+1:

**Comment by FRosner** [comment]
@Husterknupp you have a nice avatar :)

**Comment by Husterknupp** [comment]
du bist ne alte Pisshose! Kannst du Mal bitte meinen cookie von deinem MacBook löschen?

 I created a ticket for that #174

**Comment by FRosner** [comment]
Has been done in #160 already.
