### ISSUE TITLE
Treat the rabbit well

### ISSUE THREAD

**Issue by Husterknupp** [FRosner/spawncamping-dds#174]
We want to treat our collaboraeur's privacy respectfully. Even when they're dumb as fuck.  

Please remove github-cookie from FRosner's MackBuck.

Acceptance criteria
- [x] FRosner is not able to write comments on github in Husterknupp's name
- [x] FRosner is not able to change Husterknupp's avatar without. Husterknupp's permission

**Comment by FRosner** [comment]
@Husterknupp I moved it to backlog. Don't know when we will have time for it.

**Comment by Husterknupp** [comment]
No! I will close the ticket with the power of the rabbit!

**Comment by FRosner** [comment]
Noooooooo! :rabbit:

**Comment by Husterknupp** [comment]
:rabbit2:
