### ISSUE TITLE
Summarize help text not matching the implementation

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#176]
**Problem**

`help("summarize")` states that the function only works for numerical data sets. This is not true, as it selects the summarization method based on whether the data set is numeric or not.

**Solution**

The help text should properly reflect the fact that it works for both, numerical and nominal data sets.

**Comment by FRosner** [comment]
@baek86 would you like to pick this one up?

**Comment by ghost** [comment]
@FRosner 
Fixed it.

**Comment by FRosner** [comment]
@bkomboz how and where?

**Comment by ghost** [comment]
@FRosner : Just pushed my change in branch issue/176. Ready to be merged.
