### ISSUE TITLE
Online version of CorrelationAggregator

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#181]
**ToDos**
- online update of statistics to avoid double overflow with sum (http://stats.stackexchange.com/questions/72212/updating-variance-of-a-dataset/72215#72215)

**Update Covariance**

![covariance](https://upload.wikimedia.org/math/c/1/5/c150550bbd2937a7f0baadab2a0afca7.png)

**Merge two Covariances**

![merging covariance](https://upload.wikimedia.org/math/d/5/d/d5dbf91ec6c339293920a2d318ef958e.png)

**Comment by FRosner** [comment]
What is the actual difference of aggregate and mapPartitions+reduce? Do you know, @RPCMoritz ?

**Comment by FRosner** [comment]
I will only change the online update thing and leave aggregate the way it is.

**Comment by RPCMoritz** [comment]
I will perform a code review on Friday.
