### ISSUE TITLE
Include example graph data set

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#185]
**Requirements**
- free to use
- multiple connected components

**Comment by FRosner** [comment]
You can check the connected components with the connectedComponents method of DDS. It should show something nice.

**Comment by FRosner** [comment]
@zhdchen what is the progress on this one?

**Comment by zhdchen** [comment]
@FRosner a data set for peer-to-peer communication network (p2p-Gnutella08 in http://snap.stanford.edu/data/index.html) has been added. 
Please use following citation if you use it:

```
@misc{snapnets,
  author             = {Jure Leskovec and Andrej Krevl},
  title                  = {{SNAP Datasets}: {Stanford} Large Network Dataset Collection},
  howpublished  = {\url{http://snap.stanford.edu/data}},
  month              = jun,
  year                 = 2014
}
```

**Comment by FRosner** [comment]
@zhdchen Good. However, there are a few things required to complete this issue:
1. Add a GraphX graph of this data set to package.scala in datasets package
2. Provide a documentation snippet to add to the user guide example data sets section
3. Write unit tests (see other data set tests for golf and flights)

**Comment by FRosner** [comment]
@zhdchen does the dataset have multiple connected components? Can you please provide a screenshot of the connected components method of DDS here?

**Comment by zhdchen** [comment]
@FRosner a GraphX graph based on the Gnutella peer_to_peer_network.csv has been created. Also unit tests are added.

To access the graph just call this:
val graph = de.frosner.dds.datasets.enron(sc)

**Comment by zhdchen** [comment]
#### enron

``` scala
val network = de.frosner.dds.datasets.enron(sc)
```

**Comment by FRosner** [comment]
@zhdchen Thank you for the commit. Here my first comments. I will comment to commit itself inline later on.

The variable should be called `gnutella` instead of `nutella`. Also the caption should be aligned with the other captions in the section of example data set documentation.

Can you please create an issue to extend the example data set documentation by adding the source of the data? We should do that.

**Comment by FRosner** [comment]
@zhdchen can you please put a screenshot of the connected components DDS output?

**Comment by zhdchen** [comment]
@FRosner csv changed from Gnutella to Enron email network: http://snap.stanford.edu/data/email-Enron.html

**Comment by zhdchen** [comment]
@FRosner 
Screenshot of the connected components in DDS output (for Enron email network):

![graph_components](https://cloud.githubusercontent.com/assets/13234918/8847078/db540a3c-312b-11e5-993e-260f030e56ad.JPG)

**Comment by FRosner** [comment]
@zhdchen your build is failing.

**Comment by zhdchen** [comment]
@FRosner It is because I forgot to remove the unit test for calling connectedComponents with Thread sleeping. This might lead to time out. Now I've removed it and keep only the one for CSV file check. Please try it again and let me if the building this time succeeds.

**Comment by FRosner** [comment]
Will do later :) Thanks!

You are receiving an email notification to your commit address with the build result. Please consult it after your push.

**Comment by FRosner** [comment]
@zhdchen thanks for your contribution :+1:
