### ISSUE TITLE
Check if python is available in JS code formatter

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#187]
**Problem**

The `beautify-js.sh` script allows automatic code formatting for JavaScript. It requires python and the jsbeautifier package to be installed. If the user does not have python, the script will fail.

**Solution**

The script should check if python is available, e.g. `which python` and display a nice help message if not.

**Comment by ghost** [comment]
@FRosner: I solved this issue using the solution proposed [here](http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script). But I am not able to push branch issue/187.

**Comment by FRosner** [comment]
@bkomboz I granted you the rights.

**Comment by ghost** [comment]
@FRosner: Thanks! I just pushed my solution.

**Comment by FRosner** [comment]
@bkomboz I cannot see your commit here. Did you put the issue number in the commit message?

**Comment by ghost** [comment]
@FRosner: I forgot to add the tag in the message. :( Amending is not possible (I don't want to --force it ...;)

**Comment by FRosner** [comment]
@bkomboz also, your work mail should not be the one to use when you commit in your private time :)

Please change it and force the push on your branch.

**Comment by ghost** [comment]
@FRosner: Everything fixed with mighty force. ;)
