### ISSUE TITLE
State that the recommended browser is Google Chrome

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#191]
**Problem**

There are a few things where Chrome works better than, e.g., Firefox. It is faster in JS, does not block the whole browser when the visualizations are loading and it supports SVG gradients properly. Also it allows me to forget a semicolon in JS once in a while :blush: 

**Solution**

The readme file should state that Chrome is the recommended browser with the best user experience.

**Comment by ghost** [comment]
@FRosner: I just pushed a solution proposal for this issue.

**Comment by ghost** [comment]
@FRosner #191 is missing in commit message. Sorry! Next time I'll add it.

**Comment by ghost** [comment]
@FRosner: Everything fixed with mighty force. ;)

**Comment by FRosner** [comment]
@bkomboz thanks for the contribution. We might need to wait for #253 to finish before we can merge.
