### ISSUE TITLE
Build fails on systems with older git

### ISSUE THREAD

**Issue by RPCMoritz** [FRosner/spawncamping-dds#214]
`git status -sb` in build.sbt should be replaced with `git status --procelain`, in order to retain a version-independent output -- the `-b` suboption to `-s` is not supported by git 1.7.

The S3-relevant parts in buildt.sbt in general should probably be moved to a separate location (and imported/referenced from build.sbt), in order to make debugging local building easier.

**Comment by FRosner** [comment]
@RPCMoritz my suggestion is to remove the git part completely because it is not needed so far. Travis is providing the respective branch in an environment variable so we should be safe to remove the git call.

**Comment by FRosner** [comment]
@RPCMoritz I created #216 for cleaning up sbt script.

**Comment by FRosner** [comment]
@RPCMoritz thanks for the contribution.

**Comment by RPCMoritz** [comment]
QA: Now builds succesfully out-of-the-box.

**Comment by FRosner** [comment]
@RPCMoritz awesome! :ok_hand:
