### ISSUE TITLE
Cleanly split RDD user doc into RDD and DataFrame parts

### ISSUE THREAD

**Issue by RPCMoritz** [FRosner/spawncamping-dds#220]
Currently the dashboard fuction is in the same section as the other RDD functions, but I believe it merits its own section, because of the different APIs an different use cases.

**Comment by FRosner** [comment]
@RPCMoritz what do you mean by "section"? Are you talking about the help category? It is `Spark SQL` because it uses a data frame and so far the categories reflect the Spark modules / Scala. The user guide also reflects this and has sections for each category.

What is your suggested change?

**Comment by RPCMoritz** [comment]
Ah, I just clicked the link again, and it appears dissimilar to the one I based my comment on. Possibly some weird caching happened, and I was on an outdated document.
The SparkSQL heading (though not optimal in title - I would use "RDD API" and "Dataframe API") performs the sectioning I was suggesting.

**Comment by FRosner** [comment]
Good. So I can close this one up?

**Comment by RPCMoritz** [comment]
Yep
