### ISSUE TITLE
Add epsilon to avoid precision problems in covariance test

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#227]
See: https://github.com/FRosner/spawncamping-dds/commit/00eba571244782d9c6ff54f92152c234c60fb104#commitcomment-12597150

**Comment by FRosner** [comment]
Pull request created: https://github.com/FRosner/spawncamping-dds/pull/256

**Comment by Husterknupp** [comment]
Pull request (from feature branch) created:  #258

**Comment by FRosner** [comment]
Thanks again @Husterknupp
