### ISSUE TITLE
DDS runs into NPE if a case class containing null values is shown

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#245]
**How to reproduce**

```
case class A(s: String)
val rdd = sc.parallelize(List(A("a"), A("b"), A(null.asInstanceOf[String])))
show(rdd)
```

**Comment by Gerrrr** [comment]
The problem was related to `spray.json.JsString` which doesn't work on `null` values.
https://github.com/FRosner/spawncamping-dds/tree/issue/245

**Comment by FRosner** [comment]
@Gerrrr thanks for picking this up. Feel free to assign yourself when you start working on an issue so it is more visible :)

**Comment by FRosner** [comment]
@Gerrrr can you please add a corresponding test? I think there should be tests already around that check also the way the type recognition works.

**Comment by Gerrrr** [comment]
Done.

**Comment by FRosner** [comment]
Thanks @Gerrrr. I will look into it in the next days :)
