### ISSUE TITLE
Add test that checks if nothing is served when an empty sequence is shown

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#246]
**Problem**

There is no test to check that the servable is empty in case `show` is run on an empty sequence. See the [Coverage Report](https://coveralls.io/builds/3532570/source?filename=src%2Fmain%2Fscala%2Fde%2Ffrosner%2Fdds%2Fcore%2FScalaFunctions.scala#L104) for details.

**Example**

``` scala
show(List.empty)
```

**Solution**

Add a test case to `DDSTest.scala` that shows an empty sequence and checks that the resulting optional servable is empty.

**Comment by ghost** [comment]
@FRosner: Added test, see branch issue/246. Now with correct commit message.

**Comment by FRosner** [comment]
@bkomboz thanks for the contribution. I will look at it later :)
