### ISSUE TITLE
Add test that checks if nothing is served when a single-columned data frame is used for mutual information matrix computation

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#247]
**Problem**

There is no test to check that the servable is empty in case `mutualInformation` is run on a data frame that has only one column. See the [Coverage Report](https://coveralls.io/builds/3532570/source?filename=src%2Fmain%2Fscala%2Fde%2Ffrosner%2Fdds%2Fcore%2FSparkSqlFunctions.scala#L219) for details.

**Solution**

Add a test case to `DDSTest.scala` that mutual informs (:smiley:) a data frame with only one column and checks that the resulting optional servable is empty.

**Comment by Gerrrr** [comment]
Fixed in https://github.com/FRosner/spawncamping-dds/tree/issue/247.

**Comment by FRosner** [comment]
@Gerrrr thanks for the contribution! I will look into it :+1:
