### ISSUE TITLE
SUB #255: DDS Modularization

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#253]
### Problem

In order to decouple analytics from presentation and also allow adapters to different front-ends (Spark-Notebook, Zeppelin, etc.), DDS should be split into a core module and separate visualization modules.
### Solution
- DDS core project containing only
  - Scala and Spark related transformations (analytics)
  - Config-less servable case classes (data)
  - Server trait + serve method that the servable is fed to
- DDS Spray Front-End project
  - Server implementation using Spray and REST etc.
- DDS Datasets Project
#### Core Project Servable Classes

All servables share a title (`String`). Depending on the individual class, the following attributes are required:
- `BarChart`
  - Sequences of y, one per bar color (`Seq[Seq[Y]]`) + a sequence of x domain (`Seq[X]`) + a sequence of bar colors (`Seq[Z]`)
- `PieChart`
  - Category-count pairs (`Iterable[(T, N)]`, `implicit num: Numeric[N]`)
- `Histogram`
  - Bins (`Seq[Double]`)
  - Frequencies (`Seq[Long]`)
- `Table`
  - Column Names (`Seq[String]`)
  - Column Types (`StructType`)
  - Content as sequence of rows (`Seq[Seq[Any]]`)
- `Heatmap`
  - Content (`Seq[Seq[N]]`, `implicit num: Numeric[N]`)
  - Row names (`Seq[String]`)
  - Column names (`Seq[String]`)
  - Lower bound for Z scale (`N`, `implicit num: Numeric[N]`)
  - Upper bound for Z scale (`N`, `implicit num: Numeric[N]`)
- `Graph`
  - Vertices (`Seq[V]`)
  - Edges (`Iterable[(Long, Long, E)]`)
- `ScatterPlot`
  - X-Y pairs (`Seq[(X, Y)]`, `implicit numX: Numeric[X] = null, numY: Numeric[Y] = null`)
- `KeyValueSequence`
  - Key-value pairs (`Seq[(K, V)]`)
- `Composite`
  - Matrix layout of composing servables (`Seq[Seq[Servable]]`)
- `Blank`
### Open Questions & ToDo
- Where to move the manifest meta data class?
- [x] Document the removal of line chart => separate issue
- [x] Think about typed table rows / columns or not?
- [x] Create proposal for core interface to other JVM languages (probably through Java?)?
- [x] How to treat nullable in Tables that don't come from DataFrames (like RDD or Seq)? Should Option be converted or just stored in the table as provided? I think converting an RDD of Option into a Table without Option and nullable instead is cool but might also cause problems.

**Comment by FRosner** [comment]
We might want to think of a different name for `Servable` and `Server`.

**Comment by FRosner** [comment]
@Gerrrr I am not sure how to store data for bar and line charts. They could be stored just like in scatter plots, as a sequence of points. However, then it might be difficult to ensure a certain order of X and Z axis, which are categorical in the case of bar plots.

**Comment by FRosner** [comment]
@Gerrrr and I am not sure whether we should include line charts at all. I am not using them right now, although DDS provides them.

**Comment by FRosner** [comment]
@RPCMoritz do you have any thoughts on this one? What do you think would be a convenient way to represent data of a bar chart, which possibly can have multiple series.

**Comment by Gerrrr** [comment]
I think that the third option is the best for `BarChart`.
Regarding `LineChart`, I like the way it is done in [plot.ly](https://plot.ly/python/line-charts/) where line chart is just a `Scatter` with points connected with the line.

What do you think about an additional object passed to every chart (like `Marker` in plot.ly) where you can specify parameters, like axis labels, limits, logarithmic axis, etc?

**Comment by FRosner** [comment]
@Gerrrr thanks for your feedback.
1. I removed `LineChart` for now, as I am not using it for anything so far when working with DDS. We can add it later if we feel that it is needed.
2. I agree that the third option is best for `BarChart` and I will use it. Rejected options will be attached to this comment.
3. Regarding the parameter object, I think it is a good idea to provide something like this. However, I would like to move it to another iteration and for now only port the status quo (which is managing this mostly on the client side) to get the current Spray front-end connected quickly. Then we need to think how to implement this. In my opinion it needs to be in a predefined manner (so that each library knows all possible options), because this is the only way that the Spark jobs can use the configuration and make sure that the front-ends understand them.

> - Triplets of x, y and z, to allow multiple bars per x (`Seq[(X, Y, Z)]`) OR
> - Sequences of x and y, one per bar color (`Seq[Seq[(X, Y)]]`) + a sequence of bar colors (`Seq[Z]`) OR
> - Sequences of y, one per bar color (`Seq[Seq[Y]]`) + a sequence of x domain (`Seq[X]`) + a sequence of bar colors (`Seq[Z]`)

**Comment by Gerrrr** [comment]
BTW, it would be nice to be able to extend the `serve` interface not only from Scala, but also from any JVM language.

**Comment by fernandrez** [comment]
Please team, is there a way now to plot a Line Chart or has this functionality been suspended?

**Comment by FRosner** [comment]
Whoops. I removed it because I never used it and bar chart does the same. Would you like to have it again?

What is your use case? 

## 

Sent from my phone. Please excuse my brevity.

**Comment by FRosner** [comment]
You can also use scatter plots @fernandrez. But if you need them for a good reason we can include them again soon :)

**Comment by fernandrez** [comment]
Thanks a lot @FRosner, appreciate it. I am giving a try at both Bar and Scatter and will see how it goes ;)

**Comment by fernandrez** [comment]
Good day @FRosner when you say the bar chart does the same, is it that a line chart is achievable with it? If so, what options should I include for bar() function to plot lines? Thank you for you valuable time.

**Comment by FRosner** [comment]
Sorry for the confusion! :D

I meant that all, bar chart, line chart and scatter plot, can plot a 
series of values. So if you want to visualize them, most of the time a 
bar chart or scatter plot make more sense. This is because often times 
the values between two points are interpolated and don't necessarily 
make sense.

So what is it that you are trying to plot?

**Comment by fernandrez** [comment]
Understand thank you! We are plotting tendencies (payment tendencies), so we really would appreciate lines better thant bars.

**Comment by FRosner** [comment]
Gotcha. Try scatter plot for the beginning. If you really need the line 
chart, try DDS 3.x (you can also run it with Spark 1.5, only the example 
datasets don't).

Are you processing the data with Spark and then plotting it with DDS?

I just did not encounter use cases with big data where the results have 
been lines. Other than that, you could give WISP a try (WISP is scala 
plotting). They are some scala wrapper around Highcharts. But they don't 
integrate with Spark.
