### ISSUE TITLE
Make labels in chart history more informative

### ISSUE THREAD

**Issue by ghost** [FRosner/spawncamping-dds#259]
While it is nice to browse back/recreate previously created graphs/charts, the labels in the graph/chart history are not very informative. For example, after showing four different data frames, the history looks like this: 

1 - table (09:42:13)
2 - table (09:43:25)
3 - table (09:44:20)
4 - table (09:46:17)

It would be helpful to make these labels more data dependent, i.e., to add some more data specific informations (e.g., the name of the data frame shown).

**Comment by FRosner** [comment]
Agreed @bkomboz. The 'table' thingy comes from the servable type. But it would be much nicer to see the title instead. However, the name of the dataframe is not always available, since I cannot get the variable name from your script. I will pick this one up after I am done with #253 and #255

**Comment by FRosner** [comment]
This will be fixed already when merging #253
