### ISSUE TITLE
If start is invoked but port is blocked, notify the user

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#36]
**New Description**

The web server should notify the user if the port is blocked.

**Old Description**

> The web server should try a different port if the default one is blocked. This is especially useful for tests. They should not fail just because the default port is blocked. Also some users might not care which port they are using when in interactive mode.

**Comment by RPCMoritz** [comment]
I would recommend the following:

Ask the user which port to use, giving a 5-digit, unbound port as default option, only if run in interactive mode. Crash loudly in service/daemon mode.

**Comment by FRosner** [comment]
Thanks for your comment.

This is going to be the plan. As there is no other mode than the interactive one at the moment, we don't have the problem of silent failure.

I created #37 for that and scheduled it for 1.0.0-beta.

**Comment by FRosner** [comment]
@RPCMoritz I changed the issue description. I think it makes more sense to only notify, esp. as we now have the option to select a port.
