### ISSUE TITLE
Parallel coordinates view

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#46]
**Description**

In addition to a tabular view on an RDD it is possible to plot the rows in a parallel coordinates plot. `show(rdd: RDD[V])` should now offer a parallel coordinates plot as well.

The general idea is that `show(rdd: RDD[V])` transfers data in a tabular format to the front-end, while the user can work with the data there. If there are multiple plots available for tabular data (e.g. parallel coordinates plot, scatter plot, etc.) it should be selectable from the front-end rather than recomputing the results and sending it again.

**Comment by FRosner** [comment]
@milosk I will look into your commit and rebase master against the branch because the master changed a little bit since you created that branch. Can I override your branch (force push) or are you working on it currently?

I suggest we discuss again what features we would like to implement next (improved table view with selection and so on) in the next days.

**Comment by milosk** [comment]
I am not working on it currently, you can force push it.
Can you at the same time amend my commit message with "#46" (as the owner),
so that we avoid conflicts?
Get better soon!

**Comment by FRosner** [comment]
@milosk which third party libraries (other than vanilla d3) did you use? We need to make sure that their license is compliant with our and I want to add it to the readme.

**Comment by FRosner** [comment]
@milosk I rebased against master and might make some simple adjustments before merging to master. Would you mind adding your e-mail address that you used for committing to GitHub (in the settings page) so that the commit gets associated with your account?

**Comment by milosk** [comment]
sure, i used this one:
https://github.com/syntagmatic/parallel-coordinates

for the table extension we would need slickgrid.js, and for bundling
underscore.js, but we can discuss that later when i add it.

**Comment by FRosner** [comment]
@milosk ok I will create a ticket for the table extension. What does it include? Sortable table where you can select / highlight rows that get selected in the parallel coordinate view as well?

Underscore.js makes sense anyway. We can include it.

**Comment by milosk** [comment]
done

**Comment by FRosner** [comment]
Now you just need to choose the proper mail address when committing :dart: 

milos@Miloss-MacBook-Pro.local is your current one.

`git config --global user.email <proper address>`

**Comment by milosk** [comment]
Haha, funny, but that is what i did. 
I guess previous commits are not associated with the new email. Or am i missing something?

**Comment by FRosner** [comment]
Yep. If you change the configuration settings it will only apply for new commits. So in the future it should work :)

**Comment by FRosner** [comment]
I should add this functionality to the help description of `show`.
