### ISSUE TITLE
Summary of complex RDDs

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#68]
The `summarize` functions should also be able to summarize datasets that have multiple columns. This results in summaries for each column. Depending on whether we integrated `SchemaRDD`s already, it should also accept `SchemaRDD`s as input.

This requires the summary table layout for the group summaries to change - maybe plotting one summary table for each group, while each table has multiple rows - one for each column.

**Comment by RPCMoritz** [comment]
@FRosner This is probably covered by the dashboard functionality (s/SchemaRDD/Dataframe)?

**Comment by FRosner** [comment]
@RPCMoritz guess so. `summarize` works on multi-columned data frames and `dashboard` uses it. Let's close this one :+1:
