### ISSUE TITLE
Summary should contain plots

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#74]
The basic summary function `summarize` should not only show the summary statistics in a table but also produce a nice plot as an overview.
- [ ] histogram for numeric values (reuse #4 / #5)
- [ ] bar plot of counts for nominal values (reuse #73)
- [ ] summary table servable type that does not result in a parallel coordinates but only the table

This requires the summary function to serve a chart and a table. I might want to redefine the mechanism of servables to actually transmit an array of servables such that multiple servables can be sent out.

---

Depends on: #75

**Comment by FRosner** [comment]
We might consider moving this functionality to another function, because it will result in a longer run time.

So there could be a modular function for both summary statistics and histograms and a function called `profile` or `dashboard` that shows summary statistics, plots, column types, etc.

**Comment by RPCMoritz** [comment]
@FRosner you can probably close this one too? Dashboard has been implemented and provides most of the features referenced in this issue.

**Comment by FRosner** [comment]
@RPCMoritz I was thinking whether this makes sense also on an RDD basis. However, it is much more convenient to work with data frames when it comes to functions like this. I will close it however and we can open another one that is more clearly defined if new requirements arise.

Thanks for spotting it! :)
