### ISSUE TITLE
Median function for numerical RDDs

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#77]
It would be nice to have a median function. It will not be included into the normal summary function because it might be computationally expensive. We can integrate this into the dashboard function later on.

**Comment by FRosner** [comment]
Maybe we can try something like this for the median? http://www.quora.com/Distributed-Algorithms/What-is-the-distributed-algorithm-to-determine-the-median-of-arrays-of-integers-located-on-different-computers

**Comment by FRosner** [comment]
@RPCMoritz there is this solution as well http://stackoverflow.com/questions/28158729/how-can-i-calculate-exact-median-with-apache-spark

**Comment by RPCMoritz** [comment]
countByKey could potentially also be used to determine the median. Sorting the resulting Map is probably going to be the key limitation.

**Comment by FRosner** [comment]
`countByKey` will blow up the driver - don't use it :dromedary_camel:

**Comment by FRosner** [comment]
@RPCMoritz I move it to 1.5.0

**Comment by FRosner** [comment]
@RPCMoritz moving it to 1.6.0

**Comment by RPCMoritz** [comment]
Pushed basic (sorting based, for numeric values only) implementation of median into issue branch

**Comment by FRosner** [comment]
Thanks @RPCMoritz. I will look at it in the next days. As it seems to be quite expensive I will include it as a stand-alone function for now (and not include it into the summarize function).

Did you do any performance measurements on some real data set? I would like to understand the impact of this sorting.

**Comment by FRosner** [comment]
@RPCMoritz for future commits, please put the ticket number in front of the commit message so that GitHub can associate it with this issue.
