### ISSUE TITLE
Sturges formula to compute histogram bins automatically

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#92]
**Description**

There should be a histogram function that only takes an RDD and automatically determines the "optimal" number of equal-width bins.

**Signature**

``` scala
def histogram[N](values: RDD[N])(implicit num: Numeric[N])
```

**Formula**

We can use the Sturge's formula which assumes that the data is Gaussian distributed, so that the number of equal-width bins _k_ is given by

![0ced64b52339ffcef5ecf9fe9f9d3c8e](https://cloud.githubusercontent.com/assets/3427394/6752283/5b2c1082-cf0d-11e4-89fe-d75fe4a78c2f.png)

---

Relates to: #91

**Comment by FRosner** [comment]
@jviehhauser I move this to 1.6.0

**Comment by FRosner** [comment]
@RPCMoritz please change your commits to reference the issue number :)

**Comment by RPCMoritz** [comment]
@FRosner Please review and consider merging my recent commit which addresses this issue.

**Comment by FRosner** [comment]
@RPCMoritz there are merge conflicts I want to resolve first. So the review is based on the current master branch. To avoid these huge conflicts it is useful to keep feature branches only around for a short time and to rebase them often.

**Comment by FRosner** [comment]
I created https://github.com/FRosner/spawncamping-dds/pull/183 for review.

**Comment by FRosner** [comment]
@RPCMoritz you can see my inline comments in https://github.com/FRosner/spawncamping-dds/pull/183/files

**Comment by FRosner** [comment]
@RPCMoritz merged to master. Thanks for your contribution!
